name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to temp dir
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          source: ./*
          target: "/tmp/${{ vars.APP_NAME }}"

      - name: Prepare artifact
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_NAME: ${{ vars.APP_NAME }}
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          envs: APP_NAME
          script: |
            sudo chmod +x /tmp/${{ vars.APP_NAME }}/scripts/prepare.sh
            APP_NAME=$APP_NAME /tmp/${{ vars.APP_NAME }}/scripts/prepare.sh
            sudo mv /tmp/${{ vars.APP_NAME }} /var/www/${{ vars.APP_NAME }}
            python3 -m venv /var/www/${{ vars.APP_NAME }}/venv
            source /var/www/${{ vars.APP_NAME }}/venv/bin/activate
            pip install -r /var/www/${{ vars.APP_NAME }}/requirements.txt
