name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to temp dir
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          source: ./*
          target: "/tmp/${{ vars.APP_NAME }}"

      - name: Prepare artifact
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_NAME: ${{ vars.APP_NAME }}
          FOO: "bar"
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          envs: APP_NAME,FOO
          script: |
            sudo chmod +x /tmp/${{ vars.APP_NAME }}/scripts/prepare.sh
            sudo /tmp/${{ vars.APP_NAME }}/scripts/prepare.sh
